refactor: :recycle: again!

diff --git a/.github/workflows/update-outdated-packages.yml b/.github/workflows/update-outdated-packages.yml
--- a/.github/workflows/update-outdated-packages.yml
+++ b/.github/workflows/update-outdated-packages.yml
@@ -26,8 +26,18 @@ jobs:
       - name: Check for outdated packages
         id: outdated
         run: |
-            OUTDATED_PACKAGES=$(pnpm outdated -r --json)
-            echo "::set-output name=outdated::$OUTDATED_PACKAGES"
+          if OUTDATED_PACKAGES=$(pnpm outdated -r --json 2>&1); then
+            echo "Outdated packages output:"
+            echo "$OUTDATED_PACKAGES"
+            echo "$OUTDATED_PACKAGES" > outdated-packages.json
+            echo "Outdated packages file content:"
+            cat outdated-packages.json
+            echo "::set-output name=outdated::$(cat outdated-packages.json)"
+          else
+            echo "Error while fetching outdated packages:"
+            echo "$OUTDATED_PACKAGES"
+            exit 1
+          fi
 
       - name: Create pull requests for outdated packages
         id: pr
